/**
 * One-time generator for the western-states map on the homepage.
 * Projects the 11 western states from us-atlas into SVG path strings
 * so the site ships static paths with no mapping libraries at runtime.
 *
 *   node scripts/build-map.mjs
 */
import fs from "node:fs";
import { createRequire } from "node:module";
import { feature } from "topojson-client";
import { geoConicEqualArea, geoPath } from "d3-geo";

const require = createRequire(import.meta.url);
const us = require("us-atlas/states-10m.json");

const WEST = {
  "53": "WA", "41": "OR", "06": "CA", "32": "NV", "16": "ID", "30": "MT",
  "56": "WY", "49": "UT", "08": "CO", "04": "AZ", "35": "NM",
};

const WIDTH = 600;
const HEIGHT = 640;

const states = feature(us, us.objects.states).features.filter((f) => WEST[f.id]);
const collection = { type: "FeatureCollection", features: states };

const projection = geoConicEqualArea()
  .parallels([33, 45])
  .rotate([112, 0])
  .fitSize([WIDTH, HEIGHT], collection);
const path = geoPath(projection).digits(1);

const out = states
  .map((f) => {
    const [cx, cy] = path.centroid(f).map((n) => Math.round(n));
    return `  { id: "${WEST[f.id]}", name: "${f.properties.name}", cx: ${cx}, cy: ${cy}, d: "${path(f)}" },`;
  })
  .join("\n");

fs.writeFileSync(
  new URL("../src/content/westernStates.ts", import.meta.url),
  `/* Generated by scripts/build-map.mjs — do not edit by hand. */
export const MAP_WIDTH = ${WIDTH};
export const MAP_HEIGHT = ${HEIGHT};

export const WESTERN_STATES: { id: string; name: string; cx: number; cy: number; d: string }[] = [
${out}
];
`,
);
console.log(`Wrote ${states.length} states`);
