/**
 * One-time generator for the map on the homepage.
 * Projects the lower 48 states from us-atlas into SVG path strings, framed on
 * the western states (where the pilots are) with the rest of the country
 * continuing to the east. The site ships static paths with no mapping
 * libraries at runtime.
 *
 *   node scripts/build-map.mjs
 */
import fs from "node:fs";
import { createRequire } from "node:module";
import { feature } from "topojson-client";
import { geoConicEqualArea, geoPath } from "d3-geo";

const require = createRequire(import.meta.url);
const us = require("us-atlas/states-10m.json");

const WEST = new Set(["53", "41", "06", "32", "16", "30", "56", "49", "08", "04", "35"]);
// Not part of the lower 48: Alaska, Hawaii, and the territories
const EXCLUDE = new Set(["02", "15", "60", "66", "69", "72", "78"]);

// The frame: the western states fill this box; everything else extends past it
const WIDTH = 600;
const HEIGHT = 640;

const all = feature(us, us.objects.states).features.filter((f) => !EXCLUDE.has(f.id));
const west = { type: "FeatureCollection", features: all.filter((f) => WEST.has(f.id)) };

const projection = geoConicEqualArea()
  .parallels([33, 45])
  .rotate([112, 0])
  .fitSize([WIDTH, HEIGHT], west);
const path = geoPath(projection).digits(1);
// The east fades out, so whole-pixel precision is plenty there
const coarse = geoPath(projection).digits(0);

// How far east the country reaches in the same coordinates
const fullWidth = Math.ceil(path.bounds({ type: "FeatureCollection", features: all })[1][0]);

const ABBR = {
  "01": "AL", "04": "AZ", "05": "AR", "06": "CA", "08": "CO", "09": "CT", "10": "DE", "11": "DC",
  "12": "FL", "13": "GA", "16": "ID", "17": "IL", "18": "IN", "19": "IA", "20": "KS", "21": "KY",
  "22": "LA", "23": "ME", "24": "MD", "25": "MA", "26": "MI", "27": "MN", "28": "MS", "29": "MO",
  "30": "MT", "31": "NE", "32": "NV", "33": "NH", "34": "NJ", "35": "NM", "36": "NY", "37": "NC",
  "38": "ND", "39": "OH", "40": "OK", "41": "OR", "42": "PA", "44": "RI", "45": "SC", "46": "SD",
  "47": "TN", "48": "TX", "49": "UT", "50": "VT", "51": "VA", "53": "WA", "54": "WV", "55": "WI",
  "56": "WY",
};

const out = all
  .map((f) => {
    const [cx, cy] = path.centroid(f).map((n) => Math.round(n));
    const d = (WEST.has(f.id) ? path : coarse)(f);
    return `  { id: "${ABBR[f.id]}", name: "${f.properties.name}", cx: ${cx}, cy: ${cy}, d: "${d}" },`;
  })
  .join("\n");

fs.writeFileSync(
  new URL("../src/content/usStates.ts", import.meta.url),
  `/* Generated by scripts/build-map.mjs — do not edit by hand. */

/** The frame the western states are fitted to (chip positions use these units). */
export const MAP_WIDTH = ${WIDTH};
export const MAP_HEIGHT = ${HEIGHT};
/** How far the rest of the country extends to the east, in the same units. */
export const MAP_FULL_WIDTH = ${fullWidth};

export const US_STATES: { id: string; name: string; cx: number; cy: number; d: string }[] = [
${out}
];
`,
);
console.log(`Wrote ${all.length} states, full width ${fullWidth}`);
